server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${ALLOWED_ORIGINS:http://localhost:3000}"
            allowedMethods:
              - GET
              - POST
              - PATCH
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: workflow-controller
          uri: http://workflow-controller-svc:8081
          predicates:
            - Path=/api/v1/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
